export const Add_Item = 'Add_Item'
export const ClearCart = 'ClearCart'
export const Increase_Item = 'Increase_Item'
export const Decrease_Item = 'Decrease_Item'
export const Remove_Item = 'Remove_Item'
export const Update_Total = 'Update_Total'
